//ACTIONS DOS PROJETOS
export const OBTER_PROJETOS = 'OBTER_PROJETOS';
export const CADASTRAR_PROJETO = 'CADASTRAR_PROJETO';
export const EDITAR_PROJETO = 'EDITAR_PROJETO';
export const REMOVER_PROJETO = 'REMOVER_PROJETO';

//ACTIONS DAS TAREFAS
export const OBTER_TAREFAS = 'OBTER_TAREFAS';
export const CADASTRAR_TAREFA = 'CADASTRAR_TAREFA';
export const EDITAR_TAREFA = 'EDITAR_TAREFA';