// PROJETOS
export const ADICIONA_PROJETO = 'ADICIONA_PROJETO';
export const EDITA_PROJETO = 'EDITA_PROJETO';
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO';
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS';

// TAREFAS
export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS';
export const ADICIONAR_TAREFA = 'ADICIONAR_TAREFA';
export const EDITA_TAREFA = 'EDITA_TAREFA';

// NOTIFICAÇÃO
export const NOTIFICAR = 'NOTIFICAR';